task:
  name: "Firmware Dump by Dumpr"
  only_if: $CIRRUS_REPO_OWNER == 'Dumpr'
  skip: $CIRRUS_BRANCH == 'new'
  auto_cancellation: $CIRRUS_BRANCH == 'autocancel'
  timeout_in: 120m
  container:
      image: ghcr.io/sushrut1101/docker:arch
      cpu: 4
      memory: 16G

  Clone_script:
      - git clone --depth=1 --single-branch https://github.com/DumprX/DumprX.git
  Setup_script:
      - git config --global user.name "monuformirror"
      - git config --global user.email "EMILIA.WATERS@student.csn.edu"
      - cd DumprX
      - sudo bash setup.sh
  DumprX_script:
      - cd DumprX || echo "Already in the Directory"
      - ./dumper.sh $(< ${CIRRUS_WORKING_DIR}/ROM_URL.txt
